export interface tblCustomerGroup {
  id: number;
  groupCode: string | null;
  groupName: string | null;
  orgId: number | null;
  createdBy: string | null;
  lastUpdateDate: string | null;
  lastUpdatedBy: string | null;
  lastUpdateLogin: string | null;
  creationDate: string | null;
  customerCount?: number | null;
}

export interface tblCustomer {
  customerId: number;
  parentCustomerId: number | null;
  customerNumber: string | null;
  customerName: string | null;
  customerType: string | null;
  validatedFlag: string | null;
  taxReference: string | null;
  country: string | null;
  address: string | null;
  city: string | null;
  contactName: string | null;
  telephoneNumber: string | null;
  fax: string | null;
  email: string | null;
  taxCode: string | null;
  type: string | null;
  status: string | null;
  note: string | null;
  sex: string | null;
  dateOfBirth: string | null;
  customerFullName: string | null;
  otherName: string | null;
  ethnic: string | null;
  nationality: string | null;
  religion: string | null;
  nation: string | null;
  // province: string | null;
  // provinceId?: number | null;
  // district: string | null;
  // districtId?: number | null;
  // ward: string | null;
  // wardId?: number | null;
  shipToProvince:number | null;
  shipToDistrict: number | null;
  shipToWard: number | null;
  height: number | null;
  weight: number | null;
  identifiedNumber: string | null;
  effectiveDate: string | null;
  issuedBy: string | null;
  dateParty1: string | null;
  date2Party2: string | null;
  groupId: number | null;
  userName: string | null;
  avatar: string | null;
  taxCompany: string | null;
  taxAddress: string | null;
  description: string | null;
  ordercount: number | null;
  totalvalue: number | null;
  orderCountSuccess: number | null;
  totalValueSuccess: number | null;
  lastOrderDate: string | null;
  addDate: string | null;
  banned: number | null;
  loginToken: string | null;
  productReviewCount: number | null;
  questionAsk: number | null;
  questionAnswer: number | null;
  loyaltyPoint: number | null;
  loyaltyLevel: number | null;
  articleComment: number | null;
  tblCustomerSiteCommands: tblCustomerSiteCommands[] | [];
  tblCustomerSiteModels?: tblCustomerSiteCommands[] | [];
  createdBy: string | null;
  lastUpdateDate: string | null;
  lastUpdatedBy: string | null;
  lastUpdateLogin: string | null;
  creationDate: string | null;
}

export interface tblCustomerSiteCommands {
  customerSiteId: number;
  customerId: number;
  customerSiteType: string | null;
  address: string | null;
  customerSiteNumber: string | null;
  customerSiteName: string | null;
  status: string | null;
  attribute1: string | null;
  attribute2: string | null;
  attribute3: string | null;
  attribute4: string | null;
  attribute5: string | null;
  attribute6: string | null;
  attribute7: string | null;
  attribute8: string | null;
  attribute9: string | null;
  attribute10: string | null;
  attribute11: string | null;
  attribute12: string | null;
  attribute13: string | null;
  attribute14: string | null;
  attribute15: string | null;
  province: string | null;
  district: string | null;
  ward: string | null;
  effectiveDate: string | null;
  wardId: number | null;
  createdBy: string | null;
  lastUpdateDate: string | null;
  lastUpdatedBy: string | null;
  lastUpdateLogin: string | null;
  creationDate: string | null;
}
